#+TITLE:     README - OCTA Documentation
#+AUTHOR:    Takashi Hashizume
#+EMAIL:     th0x4c@gmail.com
#+OPTIONS:   num:nil toc:nil author:nil creator:nil timestamp:nil

* OCTA - Library for OCI transaction applications

** Description

OCTA is a library for OCI transaction applications.
It enables the user to generate transaction processing applications written in
Oracle Call Interface (OCI).

Executable =octa= is a simple benchmark program using OCTA library. It is
loosely based on TPC-B / TPC-C.

** Installation

Installation is done via

#+BEGIN_EXAMPLE
$ ./configure --prefix=/path/to/directory
$ make
$ make install
#+END_EXAMPLE

** License

Distributed under the BSD License.

Copyright (C) 2012, Takashi Hashizume
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

- Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.
- Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
